services:
  bosbase-node:
    image: bosbase/bosbase:ve1
    restart: unless-stopped
    environment:
      SASSPB_POSTGRES_URL: postgres://postgres:postgres@postgres-db:5432/pbosbase?sslmode=disable
      BS_ENCRYPTION_KEY: 0123456789abcdef0123456789abcdef
      OPENAI_API_KEY: ${OPENAI_API_KEY:-sk-af61vU1kIT0uw5YzOM7VRM3KGrxBAfuhVgJX9ghtkHfdRVsu}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.chatanywhere.org/v1}
      PB_ACTIVATION_VERIFY_URL: ${PB_ACTIVATION_VERIFY_URL:-https://ve.bosbase.com/verify}
      # REDIS_URL: ${REDIS_URL:-192.168.1.60:6379}
      # REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      WASM_ENABLE: ${WASM_ENABLE:-true}
      WASM_INSTANCE_NUM: ${WASM_INSTANCE_NUM:-8}
      SCRIPT_CONCURRENCY: ${SCRIPT_CONCURRENCY:-8}
      FUNCTION_CONN_NUM: ${FUNCTION_CONN_NUM:-10}
      EXECUTE_PATH: ${EXECUTE_PATH:-/pb/functions}
      # BOOSTER_PATH: ${BOOSTER_PATH:-/pb/booster-wasm}
      # BOOSTER_POOL_MAX: ${BOOSTER_POOL_MAX:-2}
      # BOOSTER_WASMTIME_MEMORY_GUARD_SIZE: ${BOOSTER_WASMTIME_MEMORY_GUARD_SIZE:-65536}
      # BOOSTER_WASMTIME_MEMORY_RESERVATION: ${BOOSTER_WASMTIME_MEMORY_RESERVATION:-0}
      # BOOSTER_WASMTIME_MEMORY_RESERVATION_FOR_GROWTH: ${BOOSTER_WASMTIME_MEMORY_RESERVATION_FOR_GROWTH:-1048576}
      PB_DATA_MAX_OPEN_CONNS: ${PB_DATA_MAX_OPEN_CONNS:-30}
      PB_DATA_MAX_IDLE_CONNS: ${PB_DATA_MAX_IDLE_CONNS:-15}
      PB_AUX_MAX_OPEN_CONNS: ${PB_AUX_MAX_OPEN_CONNS:-10}
      PB_AUX_MAX_IDLE_CONNS: ${PB_AUX_MAX_IDLE_CONNS:-3}
      PB_QUERY_TIMEOUT: ${PB_QUERY_TIMEOUT:-300s}
    ports:
      - "8090:8090"
      - "2678:2678"
    volumes:
      - ./bosbase-data:/pb/pb_data
      - ./pb_hooks:/pb_hooks
    networks:
      - basenode




networks:
  basenode:
    external: true
    name: basenode
